// Code generated by protoc-gen-go. DO NOT EDIT.
// source: prime/primepb/prime.proto

package primepb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PrimeNumber struct {
	Number               string   `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrimeNumber) Reset()         { *m = PrimeNumber{} }
func (m *PrimeNumber) String() string { return proto.CompactTextString(m) }
func (*PrimeNumber) ProtoMessage()    {}
func (*PrimeNumber) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8d5732fce9c712c, []int{0}
}

func (m *PrimeNumber) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimeNumber.Unmarshal(m, b)
}
func (m *PrimeNumber) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimeNumber.Marshal(b, m, deterministic)
}
func (m *PrimeNumber) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimeNumber.Merge(m, src)
}
func (m *PrimeNumber) XXX_Size() int {
	return xxx_messageInfo_PrimeNumber.Size(m)
}
func (m *PrimeNumber) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimeNumber.DiscardUnknown(m)
}

var xxx_messageInfo_PrimeNumber proto.InternalMessageInfo

func (m *PrimeNumber) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

type PrimeNumberManyTimesRequest struct {
	Number               *PrimeNumber `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *PrimeNumberManyTimesRequest) Reset()         { *m = PrimeNumberManyTimesRequest{} }
func (m *PrimeNumberManyTimesRequest) String() string { return proto.CompactTextString(m) }
func (*PrimeNumberManyTimesRequest) ProtoMessage()    {}
func (*PrimeNumberManyTimesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8d5732fce9c712c, []int{1}
}

func (m *PrimeNumberManyTimesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimeNumberManyTimesRequest.Unmarshal(m, b)
}
func (m *PrimeNumberManyTimesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimeNumberManyTimesRequest.Marshal(b, m, deterministic)
}
func (m *PrimeNumberManyTimesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimeNumberManyTimesRequest.Merge(m, src)
}
func (m *PrimeNumberManyTimesRequest) XXX_Size() int {
	return xxx_messageInfo_PrimeNumberManyTimesRequest.Size(m)
}
func (m *PrimeNumberManyTimesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimeNumberManyTimesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PrimeNumberManyTimesRequest proto.InternalMessageInfo

func (m *PrimeNumberManyTimesRequest) GetNumber() *PrimeNumber {
	if m != nil {
		return m.Number
	}
	return nil
}

type PrimeNumberManyTimesresponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrimeNumberManyTimesresponse) Reset()         { *m = PrimeNumberManyTimesresponse{} }
func (m *PrimeNumberManyTimesresponse) String() string { return proto.CompactTextString(m) }
func (*PrimeNumberManyTimesresponse) ProtoMessage()    {}
func (*PrimeNumberManyTimesresponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8d5732fce9c712c, []int{2}
}

func (m *PrimeNumberManyTimesresponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimeNumberManyTimesresponse.Unmarshal(m, b)
}
func (m *PrimeNumberManyTimesresponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimeNumberManyTimesresponse.Marshal(b, m, deterministic)
}
func (m *PrimeNumberManyTimesresponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimeNumberManyTimesresponse.Merge(m, src)
}
func (m *PrimeNumberManyTimesresponse) XXX_Size() int {
	return xxx_messageInfo_PrimeNumberManyTimesresponse.Size(m)
}
func (m *PrimeNumberManyTimesresponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimeNumberManyTimesresponse.DiscardUnknown(m)
}

var xxx_messageInfo_PrimeNumberManyTimesresponse proto.InternalMessageInfo

func (m *PrimeNumberManyTimesresponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*PrimeNumber)(nil), "prime.PrimeNumber")
	proto.RegisterType((*PrimeNumberManyTimesRequest)(nil), "prime.PrimeNumberManyTimesRequest")
	proto.RegisterType((*PrimeNumberManyTimesresponse)(nil), "prime.PrimeNumberManyTimesresponse")
}

func init() { proto.RegisterFile("prime/primepb/prime.proto", fileDescriptor_b8d5732fce9c712c) }

var fileDescriptor_b8d5732fce9c712c = []byte{
	// 184 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2c, 0x28, 0xca, 0xcc,
	0x4d, 0xd5, 0x07, 0x93, 0x05, 0x49, 0x10, 0x5a, 0xaf, 0xa0, 0x28, 0xbf, 0x24, 0x5f, 0x88, 0x15,
	0xcc, 0x51, 0x52, 0xe5, 0xe2, 0x0e, 0x00, 0x31, 0xfc, 0x4a, 0x73, 0x93, 0x52, 0x8b, 0x84, 0xc4,
	0xb8, 0xd8, 0xf2, 0xc0, 0x2c, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x28, 0x4f, 0xc9, 0x93,
	0x4b, 0x1a, 0x49, 0x99, 0x6f, 0x62, 0x5e, 0x65, 0x48, 0x66, 0x6e, 0x6a, 0x71, 0x50, 0x6a, 0x61,
	0x69, 0x6a, 0x71, 0x89, 0x90, 0x16, 0x8a, 0x36, 0x6e, 0x23, 0x21, 0x3d, 0x88, 0x55, 0x48, 0x7a,
	0xe0, 0x46, 0x99, 0x71, 0xc9, 0x60, 0x33, 0xaa, 0x28, 0xb5, 0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x15,
	0xe4, 0x84, 0xa2, 0xd4, 0xe2, 0xd2, 0x9c, 0x12, 0x98, 0x13, 0x20, 0x3c, 0xa3, 0x72, 0x2e, 0x21,
	0x24, 0x7d, 0xc1, 0xa9, 0x45, 0x65, 0x99, 0xc9, 0xa9, 0x42, 0x89, 0x5c, 0x22, 0xd8, 0x4c, 0x13,
	0x52, 0xc2, 0x74, 0x01, 0xba, 0xab, 0xa5, 0x94, 0xf1, 0xa8, 0x81, 0x39, 0xc7, 0x80, 0xd1, 0x89,
	0x33, 0x8a, 0x1d, 0x1a, 0x80, 0x49, 0x6c, 0xe0, 0xb0, 0x33, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff,
	0xd1, 0xf3, 0xb7, 0x1c, 0x58, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PrimeNumberServiceClient is the client API for PrimeNumberService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PrimeNumberServiceClient interface {
	// Server Streaming
	PrimeNumberManyTimes(ctx context.Context, in *PrimeNumberManyTimesRequest, opts ...grpc.CallOption) (PrimeNumberService_PrimeNumberManyTimesClient, error)
}

type primeNumberServiceClient struct {
	cc *grpc.ClientConn
}

func NewPrimeNumberServiceClient(cc *grpc.ClientConn) PrimeNumberServiceClient {
	return &primeNumberServiceClient{cc}
}

func (c *primeNumberServiceClient) PrimeNumberManyTimes(ctx context.Context, in *PrimeNumberManyTimesRequest, opts ...grpc.CallOption) (PrimeNumberService_PrimeNumberManyTimesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PrimeNumberService_serviceDesc.Streams[0], "/prime.PrimeNumberService/PrimeNumberManyTimes", opts...)
	if err != nil {
		return nil, err
	}
	x := &primeNumberServicePrimeNumberManyTimesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PrimeNumberService_PrimeNumberManyTimesClient interface {
	Recv() (*PrimeNumberManyTimesresponse, error)
	grpc.ClientStream
}

type primeNumberServicePrimeNumberManyTimesClient struct {
	grpc.ClientStream
}

func (x *primeNumberServicePrimeNumberManyTimesClient) Recv() (*PrimeNumberManyTimesresponse, error) {
	m := new(PrimeNumberManyTimesresponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PrimeNumberServiceServer is the server API for PrimeNumberService service.
type PrimeNumberServiceServer interface {
	// Server Streaming
	PrimeNumberManyTimes(*PrimeNumberManyTimesRequest, PrimeNumberService_PrimeNumberManyTimesServer) error
}

// UnimplementedPrimeNumberServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPrimeNumberServiceServer struct {
}

func (*UnimplementedPrimeNumberServiceServer) PrimeNumberManyTimes(req *PrimeNumberManyTimesRequest, srv PrimeNumberService_PrimeNumberManyTimesServer) error {
	return status.Errorf(codes.Unimplemented, "method PrimeNumberManyTimes not implemented")
}

func RegisterPrimeNumberServiceServer(s *grpc.Server, srv PrimeNumberServiceServer) {
	s.RegisterService(&_PrimeNumberService_serviceDesc, srv)
}

func _PrimeNumberService_PrimeNumberManyTimes_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PrimeNumberManyTimesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PrimeNumberServiceServer).PrimeNumberManyTimes(m, &primeNumberServicePrimeNumberManyTimesServer{stream})
}

type PrimeNumberService_PrimeNumberManyTimesServer interface {
	Send(*PrimeNumberManyTimesresponse) error
	grpc.ServerStream
}

type primeNumberServicePrimeNumberManyTimesServer struct {
	grpc.ServerStream
}

func (x *primeNumberServicePrimeNumberManyTimesServer) Send(m *PrimeNumberManyTimesresponse) error {
	return x.ServerStream.SendMsg(m)
}

var _PrimeNumberService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "prime.PrimeNumberService",
	HandlerType: (*PrimeNumberServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PrimeNumberManyTimes",
			Handler:       _PrimeNumberService_PrimeNumberManyTimes_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "prime/primepb/prime.proto",
}
